border_width = 3
margin = 6
workspace_margin = 2
# default_width = 1280
# default_height = 720
# always_float = false
default_border_color = "#1a1a1a"
floating_border_color = "#1a1a1a"
focused_border_color = "#bd93f9"
