#!/bin/sh
export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Boot picom or compton if it exists
picom --experimental-backends &

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

mpv --no-video ~/.sounds/startup.flac &

#set background
nitrogen --restore &
#xrootgif --daemon /home/greyson/gifs/spooky.gif &

libinput-gestures &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

nm-applet &

dunst &

xfce4-power-manager &

xss-lock -- betterlockscreen -l dim -- --time-str="%l:%M" &


index=0
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width
do
  barname="mainbar$index"
  monitor="$(polybar -m | awk -v i="$(( index + 1 ))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
  monitor=$monitor width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &
  index=$((index+1))
done
