modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX"]
#tags = ["Browser", "Writing", "Music", "Reading", "Steam", "Extra", "Mail"]
layouts = ["Monocle", "Fibonacci", "LeftWiderRightStack"]
layout_mode = "Tag"
insert_behavior = "Top"
scratchpad = [{ name = "Scratch", value = "kitty", x = 1110, y = 570, height = 500, width = 800 },]
window_rules = []
disable_current_tag_swap = false
disable_tile_drag = false
focus_behaviour = "Sloppy"
focus_new_windows = true

[[keybind]]
command = "Execute"
value = "~/.config/rofi/launchers/type-1/drun.sh"
modifier = ["Control"]
key = "space"

[[keybind]]
command = "ToggleFloating"
value = ""
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "Execute"
value = "~/.config/rofi/launchers/type-1/file.sh"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "Execute"
value = "~/.config/rofi/powermenu/type-1/powermenu.sh"
modifier = ["modkey"]
key = "Escape"

[[keybind]]
command = "ToggleScratchPad"
value = "Scratch"
modifier = ["modkey"]
key = "x"

[[keybind]]
command = "Execute"
value = "/home/greyson/.config/leftwm/themes/Tokyo-Night/scripts/brightdown.sh"
modifier = []
key = "XF86XK_MonBrightnessDown"

[[keybind]]
command = "Execute"
value = "/home/greyson/.config/leftwm/themes/Tokyo-Night/scripts/brightup.sh"
modifier = []
key = "XF86XK_MonBrightnessUp"

[[keybind]]
command = "Execute"
value = "/home/greyson/.config/leftwm/themes/Tokyo-Night/scripts/volup.sh"
modifier = []
key = "XF86XK_AudioRaiseVolume"

[[keybind]]
command = "Execute"
value = "/home/greyson/.config/leftwm/themes/Tokyo-Night/scripts/voldown.sh"
modifier = []
key = "XF86XK_AudioLowerVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
modifier = []
key = "XF86XK_AudioMute"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey", ]
key = "t"

[[keybind]]
command = "CloseWindow"
value = ""
modifier = ["modkey", "Control"]
key = "c"

[[keybind]]
command = "SoftReload"
value = ""
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
value = ""
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["Alt"]
key = "Tab"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["Alt", "Shift"]
key = "Tab"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Shift"]
key = "Space"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "space"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Control"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Control"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Control"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Control"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Control"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Control"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Control"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Control"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Control"]
key = "9"

[[keybind]]
command = "Execute"
value = "qutebrowser"
modifier = ["modkey"]
key = "b"

[[keybind]]
command = "Execute"
value = "thunar"
modifier = ["modkey"]
key = "n"

[[keybind]]
command = "Execute"
value = "spotify"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "Execute"
value = "ghostwriter"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "Execute"
value = "foliate"
modifier = ["modkey"]
key = "o"

[[keybind]]
command = "Execute"
value = "mailspring"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "Execute"
value = "smplayer"
modifier = ["modkey"]
key = "v"

[[keybind]]
command = "Execute"
value = "alacritty -e ranger ~/.config"
modifier = ["modkey"]
key = "r"

